name:                monomer-widgets
version:             0.1.0.0
github:              Deltaspace0/monomer-widgets
license:             MIT
author:              Ruslan Gadeev
maintainer:          rgadeew@yandex.ru
copyright:           2022 Ruslan Gadeev

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Deltaspace0/monomer-widgets#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-default
- lens
- monomer
- split
- text
- text-show
- time

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
  - Monomer.EnhancedSlider.EnhancedSliderEvent
  - Monomer.EnhancedSlider.UI
  - Monomer.SaveManager.SaveManagerEvent
  - Monomer.SaveManager.UI
  - Paths_monomer_widgets

executables:
  enhanced-slider-example:
    main:                Main.hs
    source-dirs:         examples/enhanced-slider
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monomer-widgets
  save-manager-example:
    main:                Main.hs
    source-dirs:         examples/save-manager
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monomer-widgets
  checkerboard-example:
    main:                Main.hs
    source-dirs:         examples/checkerboard
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monomer-widgets
  dragboard-example:
    main:                Main.hs
    source-dirs:         examples/dragboard
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monomer-widgets

tests:
  monomer-widgets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -w
    dependencies:
    - async
    - bytestring
    - hspec
    - monomer-widgets
    - mtl
    - stm
